### ISSUE TITLE
Error: bind EINVAL 0.0.0.0:53

### ISSUE THREAD

**Issue by A-312** [vincesafe/chatavion#1]
On windows, i got :

```
Error: bind EINVAL 0.0.0.0:53
    at state.handle.lookup (dgram.js:242:18)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Socket.onSocketError (E:\GitHub\chatavion\node_modules\node-named\lib\server.js:63:22)
    at Socket.emit (events.js:189:13)
    at state.handle.lookup (dgram.js:243:14)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

For this line : 
```
// dns chat part
server.listen(53, '0.0.0.0', function() {
  console.log('DNS server started on port 53');
});
```

**Comment by A-312** [comment]
Ok c'est un bug de node-named...

Il faut modifier le fichier server.js de node-named et mettre : 

```
        this._socket = dgram.createSocket('udp4');
```
